load("//onboard/mosaic/signals/rules:defs.bzl", "mosaic_signal")

mosaic_signal(
    name = "occupancy_seat_state_signal",
    proto = "//onboard/signals/common_types:occupancy_state_proto",
    proto_message_name = "moz_msg_OccupancyState",
    sysml_ids = ["e7380fe3-f2c7-4eac-81aa-fe4edbda709e"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "driver_occupancy_state_signal",
    proto = "//onboard/signals/common_types:occupancy_state_proto",
    proto_message_name = "moz_msg_OccupancyState",
    sysml_ids = ["609d7f99-c1a3-4c6d-acb1-c686f31ba7d7"],
    visibility = ["//visibility:public"],
)
