load("//onboard/mosaic/signals/rules:defs.bzl", "mosaic_signal")
load("//tools/build:protobuf.bzl", "mosaic_proto_library")

###############
###  Lights ###
###############

mosaic_signal(
    name = "front_left_blinker_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = [
        "a1639ebb-f463-474c-ad03-170d22144ba8",
        "68e1f99a-8726-47fb-94cf-a0425c7f24ae",
    ],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_right_blinker_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = [
        "a1639ebb-f463-474c-ad03-170d22144ba8",
        "4ddd4d51-bcd9-4572-adfd-dab583893e97",
    ],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_left_blinker_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_right_blinker_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_center_fog_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_center_fog_light_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_center_reverse_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["c05e1235-d461-4a3f-bf8a-7422dd02923c"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_center_reverse_light_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_left_brake_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["2d1e655b-97ea-4a88-9085-2f2ddf77cf1f"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_left_brake_light_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_right_blinker_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = [
        "a1639ebb-f463-474c-ad03-170d22144ba8",
        "4ddd4d51-bcd9-4572-adfd-dab583893e97",
    ],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_right_blinker_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_center_right_drl_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["b1d746e6-5e0e-4dd8-b624-60b29d22b1ba"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_center_right_drl_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_center_left_drl_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["b1d746e6-5e0e-4dd8-b624-60b29d22b1ba"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_center_left_drl_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_left_blinker_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = [
        "a1639ebb-f463-474c-ad03-170d22144ba8",
        "68e1f99a-8726-47fb-94cf-a0425c7f24ae",
    ],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_left_blinker_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_right_brake_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["2d1e655b-97ea-4a88-9085-2f2ddf77cf1f"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_right_brake_light_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_center_right_brake_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["2d1e655b-97ea-4a88-9085-2f2ddf77cf1f"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_center_right_brake_light_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_right_high_light_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["10124714-ddc7-4e5b-a099-c374a745d847"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_right_high_light_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_left_high_light_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["10124714-ddc7-4e5b-a099-c374a745d847"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_left_high_light_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_proto_library(
    name = "blinker_state_proto",
    srcs = ["blinker_state.proto"],
    visibility = ["//visibility:public"],
    with_cc = True,
    with_nanopb = True,
    with_py = True,
)

mosaic_signal(
    name = "blinker_state_signal",
    proto = "blinker_state_proto",
    proto_message_name = "moz_msg_BlinkerState",
    sysml_ids = ["5f58ec1f-814b-4b3d-93b0-6c8a12cb0361"],
    visibility = ["//visibility:public"],
)

mosaic_proto_library(
    name = "stalk_button_state_proto",
    srcs = ["stalk_button_state.proto"],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
)

mosaic_signal(
    name = "stalk_button_state_signal",
    proto = "stalk_button_state_proto",
    proto_message_name = "moz_msg_StalkButtonState",
    sysml_ids = ["46570fd1-3892-4485-89fd-a9e48eb0c0e0"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_left_drl_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["b1d746e6-5e0e-4dd8-b624-60b29d22b1ba"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_left_drl_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_right_drl_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["b1d746e6-5e0e-4dd8-b624-60b29d22b1ba"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_right_drl_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_right_drl_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["b1d746e6-5e0e-4dd8-b624-60b29d22b1ba"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_right_drl_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_left_drl_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["b1d746e6-5e0e-4dd8-b624-60b29d22b1ba"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_left_drl_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_center_left_brake_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["b1d746e6-5e0e-4dd8-b624-60b29d22b1ba"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "back_center_left_brake_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_proto_library(
    name = "turn_indicator_proto",
    srcs = ["turn_indicator.proto"],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
)

mosaic_signal(
    name = "turn_indicator_signal",
    proto = "turn_indicator_proto",
    proto_message_name = "moz_msg_TurnIndicator",
    sysml_ids = [
        "68e1f99a-8726-47fb-94cf-a0425c7f24ae",
        "4ddd4d51-bcd9-4572-adfd-dab583893e97",
    ],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_left_low_light_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["83225d5d-361e-4e33-ac12-1db3b29dd246"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_right_low_light_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightSchedule",
    sysml_ids = ["83225d5d-361e-4e33-ac12-1db3b29dd246"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_left_low_light_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_right_low_light_measured_state_signal",
    proto = "//onboard/signals/common_types:light_schedule_proto",
    proto_message_name = "moz_msg_LightState",
    visibility = ["//visibility:public"],
)

#############################
###  Zonal Breakout Power ###
#############################

mosaic_proto_library(
    name = "zonal_breakout_power_channel_proto",
    srcs = [":zonal_breakout_power_channel.proto"],
    proto_option_deps = [
        "@com_github_nanopb_nanopb//:nanopb_proto",
    ],
    with_nanopb = True,
    with_py = True,
)

mosaic_signal(
    name = "zonal_breakout_power_channel_signal",
    proto = "//onboard/signals/body:zonal_breakout_power_channel_proto",
    proto_message_name = "moz_msg_PowerChannelState",
    visibility = ["//visibility:public"],
)

mosaic_proto_library(
    name = "blinker_dance_proto",
    srcs = [":blinker_dance.proto"],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
)

mosaic_signal(
    name = "blinker_dance_signal",
    proto = "//onboard/signals/body:blinker_dance_proto",
    proto_message_name = "moz_msg_BlinkerDance",
    visibility = ["//visibility:public"],
)

mosaic_proto_library(
    name = "blinker_run_proto",
    srcs = [":blinker_run.proto"],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
)

mosaic_signal(
    name = "blinker_run_signal",
    proto = "//onboard/signals/body:blinker_run_proto",
    proto_message_name = "moz_msg_BlinkerRun",
    visibility = ["//visibility:public"],
)

mosaic_proto_library(
    name = "extern_light_app_ack_proto",
    srcs = [":extern_light_app_ack.proto"],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
)

mosaic_signal(
    name = "extern_light_app_ack_signal",
    proto = "//onboard/signals/body:extern_light_app_ack_proto",
    proto_message_name = "moz_msg_ExternLightAppAck",
    visibility = ["//visibility:public"],
)

##############
###  Doors ###
##############

mosaic_signal(
    name = "front_left_door_open_close_signal",
    proto = "door_open_close_state_proto",
    proto_message_name = "moz_msg_DoorOpenCloseState",
    sysml_ids = ["37c49694-103c-4e6c-a1a2-338f9e7d2612"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_left_door_lock_measured_state_signal",
    proto = "door_lock_measured_state_proto",
    proto_message_name = "moz_msg_DoorLockMeasuredState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_right_door_open_close_signal",
    proto = "door_open_close_state_proto",
    proto_message_name = "moz_msg_DoorOpenCloseState",
    sysml_ids = ["a7b91f2d-f6e7-453f-b698-2320b9c3b1cb"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "front_right_door_lock_measured_state_signal",
    proto = "door_lock_measured_state_proto",
    proto_message_name = "moz_msg_DoorLockMeasuredState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "rear_left_door_open_close_signal",
    proto = "door_open_close_state_proto",
    proto_message_name = "moz_msg_DoorOpenCloseState",
    sysml_ids = ["2b306def-f9ab-48d3-a083-dc0c79a46d1d"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "rear_left_door_lock_measured_state_signal",
    proto = "door_lock_measured_state_proto",
    proto_message_name = "moz_msg_DoorLockMeasuredState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "rear_right_door_open_close_signal",
    proto = "door_open_close_state_proto",
    proto_message_name = "moz_msg_DoorOpenCloseState",
    sysml_ids = ["d28b3324-ea1a-4cbe-9260-50f55ea63bf9"],
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "rear_right_door_lock_measured_state_signal",
    proto = "door_lock_measured_state_proto",
    proto_message_name = "moz_msg_DoorLockMeasuredState",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "user_door_lock_unlock_req_signal",
    proto = "user_door_lock_unlock_req_proto",
    proto_message_name = "moz_msg_UserDoorLockUnlockReq",
    visibility = ["//visibility:public"],
)

mosaic_signal(
    name = "door_lock_command_signal",
    proto = "door_lock_command_proto",
    proto_message_name = "moz_msg_DoorLockCommand",
    visibility = ["//visibility:public"],
)

mosaic_proto_library(
    name = "door_lock_command_proto",
    srcs = ["door_lock_command.proto"],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
)

mosaic_proto_library(
    name = "user_door_lock_unlock_req_proto",
    srcs = ["user_door_lock_unlock_req.proto"],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
)

mosaic_proto_library(
    name = "door_lock_measured_state_proto",
    srcs = ["door_lock_measured_state.proto"],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
)

mosaic_proto_library(
    name = "door_open_close_state_proto",
    srcs = ["door_open_close_state.proto"],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
)

mosaic_signal(
    name = "matrix_headlight_command_signal",
    proto = "matrix_headlight_command_proto",
    proto_message_name = "moz_msg_MatrixHeadlightCommand",
    visibility = ["//visibility:public"],
)

mosaic_proto_library(
    name = "matrix_headlight_command_proto",
    srcs = ["matrix_headlight_command.proto"],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
    deps = ["//onboard/signals/adas:image_and_detections_proto"],
)

mosaic_signal(
    name = "lock_button_physical_state_signal",
    proto = "//onboard/signals/common_types:button_state_proto",
    proto_message_name = "moz_msg_ButtonState",
    visibility = ["//visibility:public"],
)

mosaic_proto_library(
    name = "matrix_headlights_enable_proto",
    srcs = ["matrix_headlights_enable.proto"],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
)

mosaic_signal(
    name = "matrix_headlights_enable_signal",
    proto = "matrix_headlights_enable_proto",
    proto_message_name = "moz_msg_MatrixHeadlightsEnable",
    visibility = ["//visibility:public"],
)

mosaic_proto_library(
    name = "spoiler_position_proto",
    srcs = ["spoiler_position.proto"],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
    deps = ["//onboard/signals/common_types:si_units_proto"],
)

mosaic_signal(
    name = "spoiler_position_signal",
    proto = "spoiler_position_proto",
    proto_message_name = "moz_msg_SpoilerPosition",
    visibility = ["//visibility:public"],
)

mosaic_proto_library(
    name = "honk_flash_sequence_proto",
    srcs = [":honk_flash_sequence.proto"],
    proto_option_deps = [
        "@com_github_nanopb_nanopb//:nanopb_proto",
    ],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
)

mosaic_signal(
    name = "honk_flash_sequence_signal",
    proto = "honk_flash_sequence_proto",
    proto_message_name = "moz_msg_HonkFlashSequence",
    visibility = ["//visibility:public"],
)

mosaic_proto_library(
    name = "flash_sequence_proto",
    srcs = [":flash_sequence.proto"],
    proto_option_deps = [
        "@com_github_nanopb_nanopb//:nanopb_proto",
    ],
    visibility = ["//visibility:public"],
    with_nanopb = True,
    with_py = True,
    deps = [
        "//onboard/signals/common_types:vehicle_timestamp_proto",
    ],
)

mosaic_signal(
    name = "flash_sequence_signal",
    proto = "flash_sequence_proto",
    proto_message_name = "moz_msg_FlashSequence",
    visibility = ["//visibility:public"],
)
